version: "3"
services:
    react-app:
        image: docker.io/adiulalam/portfolio:latest
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - 8075:80
        volumes:
            - ./src:/app/src
        restart: unless-stopped