version: "3"
services:
    react-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8075:80
        expose:
            - "8075"
        volumes:
            - ./src:/app/src
        restart: unless-stopped
