version: "3"
services:
    react-app:
        image: docker.io/adiulalam/portfolio:latest
        build: 
          context: ./
          args:
            - REACT_APP_URL: ${APP_URL}
        ports:
            - 8075:80
        volumes:
            - ./src:/app/src
        restart: unless-stopped