version: "3"
services:
    react-app:
        container_name: portfolio:latest
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - 8075:80
        expose:
            - "8075"
        volumes:
            - ./src:/app/src
        restart: unless-stopped
