version: "3"
services:
    react-app:
        image: docker.io/adiulalam/portfolio:latest
        build:
          context: .
          dockerfile: Dockerfile
          args:
            - REACT_APP_URL=https://hasura.adiulalamadil.me/v1/graphql
        ports:
            - 8075:80
        volumes:
            - ./src:/app/src
        restart: unless-stopped