version: "3"
services:
    react-app:
        image: docker.io/adiulalam/portfolio:latest
        args:
          REACT_APP_URL: ${APP_URL}
        build: ./
        ports:
            - 8075:80
        expose:
            - "8075"
        volumes:
            - ./src:/app/src
        restart: unless-stopped