version: '3.8'
services:
  portfolio-db:
    container_name: portfolio-db
    image: postgres:15
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres_db -h portfolio-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  portfolio-app:
    container_name: portfolio-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    expose:
      - $PORT
    depends_on:
      portfolio-db:
        condition: service_healthy

volumes: 
  postgres-volume: