name: Portfolio Deployment

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          platforms: linux/arm64
          host: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          script: whoami
