# This is a basic workflow to help you get started with Actions

name: CD

on:
    push:
        branches: ["master"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Deploy Stack
              uses: kgierke/portainer-stack-deployment@v1
              with:
                  portainer-url: "http://132.145.17.195:9000/"
                  portainer-username: "admin"
                  portainer-password: ${{ secrets.PORTAINER_PASSWORD }}
                  portainer-endpoint: 1
                  name: portfolio
                  file: docker-compose.yml
